name: scheduled_gem_update

on: 
  push:
    branches:
    - feature/github_ci
  # schedule:
  #  - cron: 0 4 * * 6

jobs:
  bundle_update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev
        uses: actions/checkout@v2
      # https://stackoverflow.com/a/60942437
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Create new Branch
        env:
          TZ: "Asia/Tokyo"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d"`
          BRANCH_NAME="feature/gem-upgrade_$DATE"
          git checkout -b "$BRANCH_NAME"
      - name: bundle update
        run: |
          bundle update
      - name: install hub
        uses: geertvdc/setup-hub@v1.0.0
      - name: create PR
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -b master -m "[Scheduled]develop to master"
